version: 0.2

phases:
  install:
    commands:
      - echo Changing directory to viewer...
      - npm install # Install backend dependencies
      - cd viewer
      - echo Installing Node.js dependencies in the viewer directory...
      - npm install
  pre_build:
    commands:
      - echo Pre-build phase complete, starting the build...
  build:
    commands:
      - echo Starting the application from viewer...
      - npm run build # Make the React application build
  post_build:
    commands:
      - mv ./models/* ./build # Make the models (3d models) a part of the build directory
      - echo Build completed successfully.

artifacts:
  files:
    - package.json # Backend package.json required for the Elastic Beanstalk
    - package-lock.json # Backend package-lock.json required for the Elastic Beanstalk
    - viewer/build/**/* # React build artifacts
    - node_modules/**/* # Backend packages
    - app.js # Backend server
    # - "**/*" # Adjust if you want to capture artifacts specifically from viewer folder
cache:
  paths:
    - "node_modules/**/*" # Cache the node_modules in the viewer folder

